import { useEffect, useState } from 'react'
import { Check, Pencil, Sparkles } from 'lucide-react'
import { api } from '../services/api'
import type { StudentProfile } from '../types'

export default function Profile({ student, onSaved }: { student: StudentProfile; onSaved: (s: StudentProfile) => void }) {
  const [draft, setDraft] = useState(student); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  useEffect(() => { setDraft(student) }, [student])
  const save = async () => { setSaving(true); setError(''); try { const x=await api.createStudent(draft); await api.analyze(); onSaved(x); setEditing(false) } catch (err) { setError(err instanceof Error ? err.message : 'Could not save your profile.') } finally { setSaving(false) } }
  const chips=(label:string, arr:string[]) => <div className="profile-section"><h3>{label}</h3><div className="tag-list">{arr.map(x=><span className="tag" key={x}>{x}</span>)}</div></div>
  return <div><div className="page-hero"><div><span className="eyebrow">Your evolving profile</span><h1>My Profile</h1><p>These signals drive your career recommendations and roadmap.</p></div>{!editing?<button className="secondary-btn" onClick={()=>setEditing(true)}><Pencil size={16}/> Edit profile</button>:<button className="primary-btn small" onClick={save} disabled={saving}><Check size={16}/>{saving?'Saving…':'Save changes'}</button>}</div>{error && <div className="loading-box">{error}</div>}<div className="profile-layout"><div className="profile-main"><div className="profile-banner"><div className="avatar xlarge">{student.name.charAt(0).toUpperCase()}</div><div><h2>{draft.name}</h2><p>Class {draft.class_level} · {draft.board} · {draft.city}</p><span><Sparkles size={14}/> Profile is used to personalize your guidance</span></div></div><div className="profile-card-grid"><div className="info-card"><span>Academic stage</span>{editing?<select value={draft.class_level} onChange={e=>setDraft({...draft,class_level:Number(e.target.value) as 10|11|12})}><option value={10}>10th</option><option value={11}>11th</option><option value={12}>12th</option></select>:<strong>Class {draft.class_level}</strong>}</div><div className="info-card"><span>Board</span>{editing?<select value={draft.board} onChange={e=>setDraft({...draft,board:e.target.value})}><option>Maharashtra State Board</option><option>CBSE</option><option>ICSE</option><option>Other</option></select>:<strong>{draft.board}</strong>}</div><div className="info-card"><span>City</span>{editing?<input value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/>:<strong>{draft.city}</strong>}</div><div className="info-card"><span>Current goal</span>{editing?<select value={draft.goals} onChange={e=>setDraft({...draft,goals:e.target.value})}><option>I am exploring my options</option><option>I have a few careers in mind</option><option>I know my field but need a plan</option><option>I need help choosing a stream</option><option>I need college and admission guidance</option></select>:<strong>{draft.goals}</strong>}</div></div>{chips('Subjects',draft.subjects)}{chips('Interests',draft.interests)}{chips('Strengths',draft.strengths)}{chips('Work preferences',draft.work_styles)}</div><aside className="profile-side"><div className="insight-card"><span className="eyebrow">Why this matters</span><h3>Your recommendations are not permanent labels.</h3><p>As your subjects, goals, and interests change, your career map can change with them. Treat the profile as a working snapshot.</p></div></aside></div></div>
}
